apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: coffee-shop-frontend
  labels:
    app: coffee-shop
    component: frontend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/BenBaillon/openshift_labdevops2.git
      ref: main
    contextDir: frontend
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: coffee-shop-frontend:latest
  triggers:
    - type: ConfigChange