apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: coffee-shop-frontend
  labels:
    app: coffee-shop
    component: frontend
    app.kubernetes.io/name: coffee-shop-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: coffee-shop