apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: coffee-shop-frontend
  labels:
    app: coffee-shop
    component: frontend
    app.kubernetes.io/name: coffee-shop-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: coffee-shop
spec:
  to:
    kind: Service
    name: coffee-shop-frontend
  port:
    targetPort: http