apiVersion: v1
kind: Service
metadata:
  name: coffee-shop-frontend
  labels:
    app: coffee-shop
    component: frontend
    app.kubernetes.io/name: coffee-shop-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: coffee-shop
spec:
  type: ClusterIP
  selector:
    app: coffee-shop
    component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP