apiVersion: v1
kind: Secret
metadata:
  name: coffee-shop-backend-secret
  labels:
    app: coffee-shop
    component: backend
    app.kubernetes.io/name: coffee-shop-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: coffee-shop
type: Opaque
stringData:
  SECRET_API_KEY: "training-secret-key"